module.exports = {
    ASSET: 'asset',
	BALANCES: 'balance',
	RECEIVED: 'received',
	SENT: 'sent',
    ENTITY_NAME: 'Entity Name',
    ENTITY_TYPE: 'Entity Type',
    INCOMING: 'Incoming',
    OUTGOING: 'Outgoing',
    COUNTERPARTY: 'Counterparty',
    COUNTERPARTY1: 'counterparty',
    TYPE: 'type',
    ASSETS: 'assets',
    TRANSFERS: 'transfers',
    ACTIVITY: 'activity',
    DIRECT_EXPOSURE: 'Direct Exposure',
    INDIRECT_EXPOSURE: 'Indirect Exposure',
    TXN_HASH: 'txn hash',
    VALUE: 'value',
    DIRECTION: 'direction',
    DATE: 'date',
    COUNTERPARTY_SUMMARY: 'counterparty summary',
    TRANSACTION_DETAILS: 'transaction details',
    DEPOSITS: 'Deposits',
    WITHDRAWALS: 'Withdrawals',
    TOTALTRANSFERS: 'Total Transfers',
    FROM: 'from',
    TO: 'to'
};