module.exports = {
    SEARCHED_KEYWORD: 'searched=',
    CURR_CURRENCY: 'currCurrency',
    EQUAL: '=',
    AMPERSAND: '&',
    PANEL_TYPE: 'panelType',
    ADDRESS: 'address',
    PANEL_DATA: 'panelData',
    TRANSACTION: 'transaction',
    TRANSFER: 'transfer',
    CROSS_CHAIN_TRANSFER: 'crossChainTransfer',
    OP: 'op',
    BALANCES: 'balances',
    SUMMARY: 'summary',
    COUNTERPARTIES: 'counterparties',
    TRANSACTIONS:'transactions',
    RELATED_SMART_CONTRACTS: 'related smart contracts',
    ENTITY_NAME: 'Entity Name',
    ENTITY_TYPE: 'Entity Type',
    WATCH_THE_ADDRESS: 'WATCH THE ADDRESS'
};