# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Tracker UI Test Automation

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: windows-latest

    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        
    - name: Installing Node JS
      run: npm install

    - name: Installing Playwright
      run: npx playwright install

    - name: Create a new directory named artifacts
      run: mkdir artifacts

    - name: Running automated tests
      run: npm test
      env:
        BROWSER: ${{ vars.BROWSER }}
        BASE_URL: ${{ vars.BASE_URL }}
        ENABLE_TRACE: ${{ vars.ENABLE_TRACE }}
        ENABLE_VIDEO: ${{ vars.ENABLE_VIDEO }}
        USER_EMAIL: ${{ secrets.USER_EMAIL }}
        USER_PASSWORD: ${{ secrets.USER_PASSWORD }}
        ALLURE_RESULTS_DIR: "artifacts/allure-results"
        TEST_TAGS: ${{ vars.TEST_TAGS }}

    - name: Generating allure report
      if: always()
      run: npx allure generate artifacts/allure-results --clean -o artifacts/allure-report
      
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      if: always()
      with:
          name: artifacts
          path: artifacts